################################################################################
# Makefile custom para fuse
################################################################################

all: 
	gcc -DFUSE_VERSION=27 -D_FILE_OFFSET_BITS=64 -lpthread -lfuse -lbiblioteca src/sac-cli.c -o sac-cli